#!/bin/bash

set -eou pipefail
. /.functions

set_or_default BASE_PATH "/app"
set_or_default STEPPATH "${BASE_PATH}/data"
set_or_default READY_TAG "${STEPPATH}/.ready"

say "👉 Checking readiness marker..."
is_file "${READY_TAG}" || fail "Not Ready!"
say "\t✅ Ready!"
exit 0
