#!/bin/bash
set -eou pipefail

timestamp()
{
	/usr/bin/date -Ins
}

say()
{
	echo -e "$(timestamp): ${@}"
}

fail()
{
	say "❌ ${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

[ -v STEPPATH ] || STEPPATH=""
[ -n "${STEPPATH}" ] || STEPPATH="/app/data"

[ -v READY_TAG ] || READY_TAG=""
[ -n "${READY_TAG}" ] || READY_TAG="${STEPPATH}/.ready"

say "👉 Checking readiness marker..."
[ -f "${READY_TAG}" ] || fail "Not Ready!"
say "\t✅ Ready!"
exit 0
