#!/bin/bash
set -eo pipefail

[ ${#} -ge 1 ] || set -- "1"

STEP_PID="${1}"

# We wait until it's up an listening, for up to 90 seconds, and we also
# keep watch to see if it crashes
START="$(/usr/bin/date +%s)"
MAX_WAIT="90"
echo "👉 Waiting for the daemon to complete its startup (for up to ${MAX_WAIT} seconds)..."
while true ; do

	# If it's up, end the poll
	/usr/bin/curl -kL https://localhost:9000/root.pem &>/dev/null && break

	# It's not up ... is it still running?
	if ! kill -0 "${STEP_PID}" &>/dev/null ; then
		# Not running anymore, complain loudly and quit
		echo "❌ The step-ca daemon died while we waited for it to start up"
		exit 1
	fi

	# It's not up yet, but still running ... have we timed out?
	NOW="$(/usr/bin/date +%s)"
	if [ $(( NOW - START )) -ge 90 ] ; then
		echo "❌ The step-ca daemon did not start after ${MAX_WAIT} seconds, failing"
		exit 1
	fi

	# It's not up yet, and hasn't timed out, so just sleep
	sleep 1
done
echo "👉 Daemon is up!"

[ -v DOCKER_STEPCA_INIT_X509_DURATION ] || DOCKER_STEPCA_INIT_X509_DURATION="13140h"
echo "👉 Reconfiguring the default provisioner's certificate duration to [${DOCKER_STEPCA_INIT_X509_DURATION}]"
if ! /usr/bin/step ca provisioner update admin --x509-max-dur="${DOCKER_STEPCA_INIT_X509_DURATION}" --x509-default-dur="${DOCKER_STEPCA_INIT_X509_DURATION}" ; then
	echo "❌ Failed to reconfigure the X509 duration to [${DOCKER_STEPCA_INIT_X509_DURATION}]"
fi

# TODO: Other reconfigurations?

echo "👉 Signaling the step-ca process (pid=${STEP_PID})"
kill -HUP "${STEP_PID}" || echo "❌ Failed to send the HUP signal to the step-ca process (pid ${STEP_PID})"
echo "👉 Reconfiguration complete!"
